[2021-04-09 16:49:50,355][logconsumer:18][INFO][123145406287872] - 邮件配置错误！
[2021-04-09 17:02:21,895][logconsumer:18][INFO][123145467158528] - f1 run
[2021-04-09 17:02:23,908][logconsumer:18][INFO][123145467158528] - f1 failed Traceback (most recent call last):
  File "/Users/wangfeihong/Desktop/TaskManager/task.py", line 75, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wangfeihong/Desktop/TaskManager/task_code/f1.py", line 6, in run
    raise Exception('错误1！！')
Exception: 错误1！！

[2021-04-09 17:02:41,876][logconsumer:18][INFO][123145467158528] - 邮件发送成功！
[2021-04-09 17:03:21,081][logconsumer:18][INFO][123145413664768] - f1 run
[2021-04-09 17:03:23,085][logconsumer:18][INFO][123145413664768] - f1 failed Traceback (most recent call last):
  File "/Users/wangfeihong/Desktop/TaskManager/task.py", line 75, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wangfeihong/Desktop/TaskManager/task_code/f1.py", line 6, in run
    raise Exception('错误1！！')
Exception: 错误1！！

[2021-04-09 17:03:24,691][logconsumer:18][INFO][123145413664768] - 邮件发送成功！
[2021-04-09 17:09:26,933][logconsumer:18][INFO][123145413664768] - f1 run
[2021-04-09 17:09:28,935][logconsumer:18][INFO][123145413664768] - f1 failed Traceback (most recent call last):
  File "/Users/wangfeihong/Desktop/TaskManager/task.py", line 75, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wangfeihong/Desktop/TaskManager/task_code/f1.py", line 6, in run
    raise Exception('错误1！！')
Exception: 错误1！！

[2021-04-09 17:09:29,756][logconsumer:18][INFO][123145413664768] - 邮件发送成功！
[2021-04-09 17:14:49,302][logconsumer:18][INFO][123145413664768] - f1 run
[2021-04-09 17:14:51,307][logconsumer:18][INFO][123145413664768] - f1 failed Traceback (most recent call last):
  File "/Users/wangfeihong/Desktop/TaskManager/task.py", line 75, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wangfeihong/Desktop/TaskManager/task_code/f1.py", line 6, in run
    raise Exception('错误1！！')
Exception: 错误1！！

[2021-04-09 17:14:51,889][logconsumer:18][INFO][123145413664768] - 邮件发送成功！
